version: 2
jobs:
  build:
    machine: true
    steps:
      - setup_remote_docker
      - checkout
      - run: docker build -f Dockerfile.test .
      - run: pyenv install miniconda3-4.3.11
      - run: pyenv local miniconda3-4.3.11
      - run: python tests/run_notebook_tests.py
